### PR TITLE
Cleaned up grammar and capitalization of README.md

### PR DESCRIPTION
**Pull request by savagemike**
cleaned up a bit of grammar and capitalization

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Thank you @savagemike for your contribution! We received two PRs before yours. Therefore, I merged the first into `develop` branch, and I requested to the second contributor to re-submit his updates. After this, I will request you to apply your changes on top of latest `develop`. I will let you know.

**Comment by rmariuzzo** [comment]
@savagemike the previous contributor didn't respond after 48hrs. If you are still willing to submit your changes, please pull latest changes from `develop` branch, apply your changes and update this PR.

**Comment by savagemike** [comment]
Hello!

How do I pull the changes from the `develop` branch to my fork? Sorry, I'm a bit of a Github noob

**Comment by rmariuzzo** [comment]
Don't worry @savagemike! Just make your changes on your `patch-1` branch. Or here, click on the files changed tab and then edit.

**Comment by savagemike** [comment]
hello @rmariuzzo I've submitted the PR! Thanks! 😁

**Pull request closed without merging**
