### PR TITLE
#Hactoberfest: Fix LGTM issues #109

### PR DESCRIPTION
**Pull request by celinrayen**
Fixed the 26 Errors reported in LGTM.

### CODE REVIEW

**Comment by rmariuzzo** [comment]
This pull request **introduces 4 alerts** and **fixes 23** when merging 830a5e3731bb903ac77590b74047ae7083e22dbe into 5ee675cb81c15ca1f36efe159363b3c11af6b401 - [view on LGTM.com](https://lgtm.com/projects/g/developersdo/opensource/rev/pr-e34ab59ae841d65a0fb4f7a56569799a55ca71ef)

**new alerts:**

* 4 for Unused or undefined state property

**fixed alerts:**

* 23 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by rmariuzzo** [comment]
This pull request **introduces 4 alerts** and **fixes 25** when merging d56a3c7bc539fc79add63d6734386844d718e9af into 5ee675cb81c15ca1f36efe159363b3c11af6b401 - [view on LGTM.com](https://lgtm.com/projects/g/developersdo/opensource/rev/pr-5026a0bdf1fda248bda5ef2fecd0ca103952a1ce)

**new alerts:**

* 4 for Unused or undefined state property

**fixed alerts:**

* 25 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by celinrayen** [comment]
I'm not pretty sure about the alert : `NEWComponent state property 'error' is 2 Values, but it is never read.`. Hence not cleared that yet. On my opinion, the property `error` in `state` is set later from the promise return. It can be used in later point of time to display/handle errors in the component.

Please let me know in case of any changes.

**Comment by rmariuzzo** [comment]
@celinrayen can you resolve the conflicts? After that, I will review your changes. :-)

**Comment by rmariuzzo** [comment]
This pull request **introduces 4 alerts** and **fixes 24** when merging 67ef772b9849454b59be1733a349b9f67cfed6e0 into ed666826345b9ab7713ee49faf58ae2a39824434 - [view on LGTM.com](https://lgtm.com/projects/g/developersdo/opensource/rev/pr-89cfe3d6505ca6a110a3f858944fde404fb47663)

**new alerts:**

* 4 for Unused or undefined state property

**fixed alerts:**

* 24 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by rmariuzzo** [comment]
This pull request **fixes 24 alerts** when merging 505485e67f977521cf1b9b57385cbcef85549b39 into ed666826345b9ab7713ee49faf58ae2a39824434 - [view on LGTM.com](https://lgtm.com/projects/g/developersdo/opensource/rev/pr-7897e600dbe047e189ad097498466b80523c3e23)

**fixed alerts:**

* 24 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by rmariuzzo** [comment]
Fixes: #109.

**Comment by rmariuzzo** [comment]
Thank you a lot @celinrayen! Good job!

**Comment by samlanning** [comment]
@celinrayen Thanks for fixing some LGTM alerts, and congratulations for your #Hacktoberfest contribution!

Given you've now made some contributions, you may also be interested in signing up for the LGTM GitHub Universe competition here: https://competitions.lgtm.com/ghu-2018 Each alert you fix / have fixed in the time the competition is running will result in us giving a donation to the WWF. There's also a chance that you could win some prizes!

Let me know if you have any questions!

**Pull request merged**
