### PR TITLE
Scrape script

### PR DESCRIPTION
**Pull request by uLan08**
Addresses #21

### CODE REVIEW

**Comment by DannyFeliz** [comment]
@uLan08 please fix the conflicts

**Comment by rmariuzzo** [comment]
@uLan08 pull changes from `develop` branch and rebase your changes on it.

**Comment by uLan08** [comment]
For some reason, I can't run `userScraper.scrape()`  it's saying `Cannot scrape completely TypeError: usersScraper.scrape is not a function`

**Comment by rmariuzzo** [comment]
@uLan08 will check it later today.

**Comment by rmariuzzo** [comment]
@uLan08 I want to let you know that this feature was implemented by #33. If you are still willing to collaborate in this project you could check both scripts: `generate-data.js` and `scrape.js` and make them look similar. :)

**Pull request closed without merging**
